header:
  version: 18
distro: poky
machine: qemux86-64
target: core-image-minimal
repos:
  yocto-sandbox:
  yocto:
    url:  https://git.yoctoproject.org/poky
    branch: master
    path: sources/poky.git
    layers:
      meta:
      meta-poky:
  meta-openembedded:
    url: https://git.openembedded.org/meta-openembedded
    branch: master
    path: sources/meta-openembedded.git
    layers:
      meta-oe:
      meta-python:
      meta-networking:
      meta-filesystems:
      meta-multimedia:
      meta-gnome:
bblayers_conf_header:
  base: |
    BBLAYERS_NON_REMOVABLE ?= " \
      ${TOPDIR}/../../sources/poky.git/meta \
      ${TOPDIR}/../../sources/poky.git/meta-poky"
local_conf_header:
  base: |
    CONF_VERSION = "2"
    BB_NUMBER_THREADS = "${@min(20, bb.utils.cpu_count())}"
    PARALLEL_MAKE = "-j ${@min(20, bb.utils.cpu_count())}"
    INIT_MANAGER = "systemd"
    VIRTUAL-RUNTIME_syslog = ""
    VIRTUAL-RUNTIME_base-utils-syslog = ""
    VIRTUAL-RUNTIME_initscripts = ""
    PACKAGE_CLASSES ?= "package_rpm"
    PATCHRESOLVE ?= "noop"
    PACKAGECONFIG:append_pn-qemu-native = " sdl"
    IMAGE_FSTYPES = "wic wic.bz2"
    USER_CLASSES ?= "buildstats"
    BB_DISKMON_DIRS ??= "\
        STOPTASKS,${TMPDIR},1G,100K \
        STOPTASKS,${DL_DIR},1G,100K \
        STOPTASKS,${SSTATE_DIR},1G,100K \
        STOPTASKS,/tmp,100M,100K \
        HALT,${TMPDIR},100M,1K \
        HALT,${DL_DIR},100M,1K \
        HALT,${SSTATE_DIR},100M,1K \
        HALT,/tmp,10M,1K"
